### ISSUE TITLE
Support for access to arguments array in DebugStackFrame

### ISSUE THREAD

**Issue by smarr** [graalvm/graal#207]
With `SuspendedEvent.getFrame()` being deprecated, it seems we are going to lose access to the arguments array of a stack frame.

The new `DebugStackFrame` can only access slots as far as I can make out.

Being able to access the arguments array is necessary to provide full debugger support for my language.

I did not sketch a solution so far, because it feels here might be more work necessary. Perhaps there is even the need for support of argument array 'layouts' in the `FrameDescriptor`. Don't know for sure.

What would be the best way forward?

Ping possibly interested parties: @jtulach @mlvdv @entlicher @eregon @chumer

**Comment by chumer** [comment]
Why do you need access? Does your language not write every argument into a frame slot after the function was called?

**Comment by smarr** [comment]
My language does not transfer the values from the arguments array to the frame, no.

Writing to the frame slot has no measurable benefit, and only drawbacks for interpreter speed. Arguments can't be changed, so, there is no real benefit from specializing on their type.

See for interpreter speed overhead: http://stefan-marr.de/papers/oopsla-marr-ducasse-meta-tracing-vs-partial-evaluation/#x1-270024

See for peak performance speed: http://stefan-marr.de/papers/oopsla-marr-ducasse-meta-tracing-vs-partial-evaluation/#x1-300016

It is labeled 'typed args' in both cases. Even for peak performance, there are few benchmarks that benefit. Overall it causes even a slight slowdown.

**Comment by chumer** [comment]
>  Arguments can't be changed, so, there is no real benefit from specializing on their type.

Arguments can be polymorphic and have unknown types. Type speculation is still necessary.

I have no problem exposing the arguments array as DebugValue as well. But they won't have names then.

**Comment by smarr** [comment]
Not having names is less than ideal for tooling.

And, my data shows that type speculation does not bring anything for my language, but that's somewhat another discussion.

**Comment by chumer** [comment]
I guess we could add another API that allows to describe the names of arguments. We need to hide internal stuff there anyway.

Type speculation does not bring you anything, because Truffle speculates by default on parameter types. For polymorphic parameter types you still need speculation on your own.

**Comment by entlicher** [comment]
Arguments also contain `this` for languages that have it. And `this` is currently inaccessible.
I'm not sure how to treat it in a language-agnostic way, but when names are added and when this is named as "this" by the language, then it will show up in the list of variables, at least.
But since we have `PolyglotEngine.Language.getGlobalObject()`, we should probably have a representation for `this` as well...

**Comment by entlicher** [comment]
There is now DebugScope.getArguments() providing the list of arguments.
https://github.com/graalvm/graal/commit/73d43fa94ade572e5d6180b6dad7b7d1f268a86b

**Comment by smarr** [comment]
Great, thanks. Closing the issue.
