### ISSUE TITLE
Lingering state in GraalIR graph selects the wrong constructor method

### ISSUE THREAD

**Issue by sertel** [graalvm/graal#234]
Hi,

in a research project, we are trying to do the following:
```java
public int challenge() {
  // The task: in the GraalIR we would like to change the type of the list 
  // to MyList (see definition below) that also implements the list interface. 
  //(see NewInstanceNodeReplacementPhase)
  List<Integer> l = new ArrayList<>(5); // runtime -> Problem: this does not call 
                                        // MyList.<init>(int) but still calls ArrayList.<init>(int).
		
  // print the list type to check if we were successful
  System.out.println(l.getClass()); // runtime: this prints “MyList”
		
  l.add(23); // runtime: uses MyList.add(Object)
  return l.get(0); // runtime: uses MyList.get(int)
}
```
So we try to change the type of `l` to type `MyList` that also implements `List`. 
```java
class MyList extends ArrayList<Integer> {
  public MyArrayList(int defaultSize) {
    super(defaultSize);
    System.out.println("initializing MyArrayList with default size " + defaultSize);
  }
	
  @Override
  public boolean add(Integer element) {
    return super.add(element+2);
  }
}
```
What happens is that all nodes in the `StructuredGraph` that were previously referencing `List` or `ArrayList` are now referencing `MyList`. However, the constructor being called is not the one of `MyList` but the one of `ArrayList`.

I do not see why this should be the case. It seems like there is state inside the `StructuredGraph` that is not updated once a node is being replaced.

On a side note I find it very weird what is happening here: We get an instance of `ArrayList` which is treated like a `MyList`. If I would define new variables in `MyList` and access them inside the `MyList.add(Object)` function then in this current configuration it would break the safety of the type system, right? Does Graal not run any type analysis on the graph to make sure the program/graph is still type safe after the transformations have been performed? I would have expected such a check to happen at least for the runs of the high tier phase.

The minimal working example of this issue can be found here:
https://gist.github.com/yoook/f24e0c81392ef1e987590b91f1691a94
We would be grateful for any help with this because this is a student thesis and therewith has a firm deadline.

Cheers,
Sebastian.

**Comment by gilles-duboscq** [comment]
Hi Sebastian, i assume you already looked at the graph in the [IGV] to check that they were transformed as you expect.

A few remarks:
* You replace the call to the constructor, but what about `add` and `get` at this point they could already have been devirtualized to exactly call the `ArrayList` methods.
* Did you check that the code you compiled with Graal is executed to completion? It could deoptimize before you reach anything where `ArrayList` and `MyArrayList` differ.
* Type safety of the program is ensure by the VM when it verifies the bytecodes. Graal assumes that bytecode verification was successful. You can also run with assertions enabled (`-ea -esa`) to get more sanity checks during the compilation.

In general though, I see 2 problems with the current approach:
* The transformation is done too late: the compiler already had time to assume that the allocated object was *exactly* an `ArrayList` it can have done any number of transformations that you will not be able to revert when you break that assumption.

  You could use a [`NodePlugin`] to intercept the creation of the `NewInstance` node and change it directly in the graph builder, before it had a chance to influence the rest of the compilation.
* This type of transformation is very fragile because of deoptimization: if deoptimization occurs, execution will continue in the interpreter where the transformation didn't take place.

 Gilles


[IGV]: https://github.com/graalvm/graal/blob/master/compiler/docs/Debugging.md#dumping
[`NodePlugin`]: https://github.com/graalvm/graal/blob/master/compiler/src/org.graalvm.compiler.nodes/src/org/graalvm/compiler/nodes/graphbuilderconf/NodePlugin.java#L158

**Comment by sertel** [comment]
Hi Gilles,

thanks a lot for taking the time to address this issue.
Yes, we already checked the graph in the IGV and everything looks fine there. 
And it is true that the compiler already creates nodes for `ArrayList.get` and `ArrayList.add` instead of only for `List.get` and `List.add`.
However, after our change, all the nodes that referenced `ArrayList` before are now referencing `MyArrayList` including the calls to `get` and `add`.
I guess instead of print outs we could have also just placed from kind of assertion checks there.

Thanks for the hint with the `NodePlugin`, we will definitely try it out.
We already dug deep in order to understand where this propagation of the actual type is happening and found the according code in the `ByteCodeParser`.  I'm not even sure whether a NodePlugin will execute before that is going to happen.

With respect to deoptimization, I believe that we are safe because our transformation is only a first step in a series of transformations that eventually produces OpenCL code. So whatever deoptimization strategy works for the OpenCL transformation also works for us.

However, on a general note:
Should this transformation work?
Why do you think, it does not work or why do you think it does not work as expected?
Are there types of transformations that should not be performed on the Graal IR?

Thanks again for your help on this,
Sebastian.

**Comment by sertel** [comment]
So I finally found that "lingering" state: it is the reference to the `ArrayList.init(int)` method in the constant pool of the `challenge` function. I could not find a way to alter something there because the resolved method object and therewith the constant pool is build in a native function called `CompilerToVM.asResolvedJavaMethod()`. 

So I tried to wrap the resulting `ResolvedJavaMethod` and the included `ConstantPool` such that the latter returns me `MyList.init(int)` whenever `ArrayList.init(int)` was requested. The result is a segmentation fault. :(

Is there any chance to change the constant pool?
Do you see any other option to make this work?

Cheers,
Sebastian.

**Comment by gilles-duboscq** [comment]
Hi Sebastian,

Changing references to `ArrayList` to `MyArrayList` after the fact doesn't really change the fact that parts of the graph might have been built in a way that depend on the object being exactly an `ArrayList`: the bytecode parser can do some limited inlining for example, or some simplifications.

The `NodePlugin` will be called before the nodes are inserted in the graph by the bytecode parser. For example, `handleNewInstance` is called before the `NewInstance` node is created.

I'm not too surprised by the segmentation fault as hotspot expects the compiler to produce code that conforms to the bytecode and it assumes so in various places. Especially around stack walking and deoptimization. You can take some liberties but problems appear very quickly if you add java method calls that didn't exist in the bytecode or call different methods.

One option you have is to transform the bytecodes.
An other one is to apply your transformations later in the compilation process and restrict yourself to regions of the graph that don't contain any `DeoptimizingNode` which return true for  `canDeoptimize()`. These deoptimization-free zone are not really observable from the VM.

**Comment by sertel** [comment]
I finally implemented it as a bytecode transformation via ASM, so you can close this issue.
However, it leaves me puzzled on what transformations are actually possible with the GraalIR.

Anyways, thanks for your help!
Sebastian.

**Comment by gilles-duboscq** [comment]
Glad to hear you found a solution.

If you want to run the final code on HotSpot, you are constrained in the transformation you do on the IR: the transformations have to respect the semantics of the bytecode program.
The second aspect is that transformations that change semantics have to happen before the old information has a chance to be used and propagated into the rest of the IR. The current bytecode parser already does some simple optimizations which is why such transformation have to be applied *during* bytecode parsing using the various parsing plugins.
